language: node_js
node_js: node
os: linux
dist: trusty

env:
  global:
    - TZ=Asia/Shanghai

git:
  depth: false
  submodules: false

cache:
  apt: true
  directories:
    - node_modules

before_install:
  # Git Config
  - git config --global user.name "ritboy"
  - git config --global user.email "ritboylei@gmail.com"

  # clone blog code
  - git clone -b ritboy https://${GITHUB_TOKEN}@github.com/ritboylei/blog-code-ritboy.git blog-code
  - cd ./blog-code
  - sed -i "s#https://github.com/ritboylei/ritboylei.github.io.git#https://${GITHUB_TOKEN}@github.com/ritboylei/ritboylei.github.io.git#g" _config.yml
  - sed -i "s#https://e.coding.net/ritboy/blog.git#https://${CODING_USER}:${CODING_TOKEN}@e.coding.net/ritboy/blog.git#g" _config.yml

  # Restore last modified time
  - "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"

  # Submodules
  - git clone https://${GITHUB_TOKEN}@github.com/ritboylei/hexo-theme-ritboy.git themes/ritboy

install: npm install

script:
  - hexo clean
  - hexo g -d

